# Generated by Django 5.1.6 on 2025-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0003_remove_report_assets_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorpreregistration',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
